/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "system_stm32f4xx.h"
#include "timer.h"
#include "eventman.h"
#include "led.h"
#include "melody.h"
#include "lightsensor.h"
#include "temhumsensor.h"
#include "eventbutton.h"
#include "button.h"
#include "Ucglib.h"
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "uartcmd.h"
#include "serial.h"

void AppInitCommon(void);
static void AppStateManager(uint8_t);


typedef enum {
	EVENT_EMPTY,
	EVENT_APP_INIT,
	EVENT_APP_FLSUHMEM_READY
} event_api_t;

typedef enum {
	STATE_APP_STARTUP,
	STATE_APP_IDLE,
	STATE_APP_RESET
} state_app_t;
static ucg_t ucg;
state_app_t eCurrentSate;

static void SetStateApp(state_app_t state);
static state_app_t GetStateApp(void);
void LoadConfiguration();
void DeviceStateMachine(uint8_t);
void delay_ms(uint32_t millisecond);
int isPressed = 0;
void Task_multiSensorScan(void);
void lightIncrease(void *arg);
void lightDecrease(void *arg);
void LedCmdSetState(uint8_t led_id, uint8_t led_color, uint8_t led_num_blink, uint8_t led_interval, uint8_t led_last_state);
void BuzzerCmdSetState(uint8_t buzzer_state);
void LcdCmdSetState(char* str);
static char src1[20] = "";
static char src2[20] = "";
static char src3[20] = "";
static uint32_t time_current, time_initial, time_total;
static uint8_t temperature, humidity, light;
#define CYCLE_SEND_DATA 10000 // ms

static SSwTimer idTimerDimmerLevelChange = NO_TIMER;
//Khởi tạo
void AppInitCommon(void)
{
	SystemCoreClockUpdate();
	TimerInit();
	EventSchedulerInit(AppStateManager);
	EventButton_Init();
	BuzzerControl_Init();
	LedControl_Init();
	LightSensor_Init(ADC_READ_MODE_POLLING);
	TemHumSensor_Init();
	Ucglib4WireSWSPI_begin(&ucg, UCG_FONT_MODE_SOLID);

	ucg_ClearScreen(&ucg);
	EventSerial_Init();

	EventSerial_SetEventLedCallback(LedCmdSetState);
	EventSerial_SetEventBuzzerCallback(BuzzerCmdSetState );
	EventSerial_SetEventLcdCallback(LcdCmdSetState);
	ucg_SetColor(&ucg, 0, 255, 255, 255);

	ucg_SetColor(&ucg, 1, 0, 0, 0);

	ucg_SetRotate180(&ucg);


}

//trạng thái app
static void AppStateManager(uint8_t event)
{
	switch(GetStateApp())
	{
		case STATE_APP_STARTUP:
			if(event == EVENT_APP_INIT)
				SetStateApp(STATE_APP_IDLE);
				LoadConfiguration();

			break;
		case STATE_APP_IDLE:
			DeviceStateMachine(event);
			break;
		case STATE_APP_RESET:
			break;
		default:
			break;
	}
}

static void SetStateApp(state_app_t state)
{
	eCurrentSate = state;
}
static state_app_t GetStateApp(void)
{
	return eCurrentSate;
}
//Khởi tạo ban đầu
void LoadConfiguration()
{
	ucg_SetFont(&ucg, ucg_font_9x15_tr);
	ucg_DrawString (&ucg, 50, 20, 0, "IOT");
	ucg_DrawString (&ucg, 0, 40, 0, "Programming by");
	ucg_DrawString (&ucg, 0, 60, 0, "Lumi Smarthome");
	char* str = "Board STM32F401RE";
	Serial_SendPacket(CMD_OPT_NOT_USE, CMD_ID_LCD, CMD_TYPE_SET, str, (strlen(str)+1)/sizeof(char));
}
unsigned int level = 0;
//Hàm nhận cac sự kiện
void DeviceStateMachine(uint8_t event)
{
	switch(event)
	{
		case EVENT_OF_BUTTON_3_PRESS_5_TIMES:
		{
			LedControl_BlinkStart(LED_ALL_ID, BLINK_GREEN, 10, 500, LED_COLOR_BLACK);
			ucg_ClearScreen(&ucg);
			ucg_SetFont(&ucg, ucg_font_04b_03_hf);
			ucg_DrawString (&ucg, 0, 10, 0, "Device: Board STM32 Nucleo");
			ucg_DrawString (&ucg, 0, 20, 0, "Code: STM32F401RE_NUCLEO");
			ucg_DrawString (&ucg, 0, 30, 0, "Manufacturer: STMicroelectronics");
			ucg_DrawString (&ucg, 0, 40, 0, "Kit expansion: Lumi Smarthome");
			ucg_DrawString (&ucg, 0, 50, 0, "Project: Simulator touch switch");
			time_total = 0;
		}
		break;
		case EVENT_OF_BUTTON_1_PRESS_LOGIC:
		{
			if(isPressed == 0)
			{
				isPressed = 1;
				LedControl_SetAllColor(LED_COLOR_RED, 100);
				LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_RED, 100);
				LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_RED, 100);
				BuzzerControl_SendPacketRespond(1);
				BuzzerControl_SetMelody(pbeep);
			}
			else
			{
				isPressed = 0;
				LedControl_SetAllColor(LED_COLOR_RED, 0);
				LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_RED, 0);
				LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_RED, 0);
				BuzzerControl_SendPacketRespond(1);
				BuzzerControl_SetMelody(pbeep);
			}

		}
		break;
		case EVENT_OF_BUTTON_2_PRESS_LOGIC:
		{
			if(isPressed == 0)
			{
				isPressed = 1;
				LedControl_SetAllColor(LED_COLOR_GREEN, 100);
				LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_GREEN, 100);
				LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_GREEN, 100);
				BuzzerControl_SendPacketRespond(1);
				BuzzerControl_SetMelody(pbeep);
			}
			else
			{
				isPressed = 0;
				LedControl_SetAllColor(LED_COLOR_GREEN, 0);
				LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_GREEN, 0);
				LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_GREEN, 0);
				BuzzerControl_SendPacketRespond(1);
				BuzzerControl_SetMelody(pbeep);
			}
		}
		break;
		case EVENT_OF_BUTTON_5_PRESS_LOGIC:
		{
			if(isPressed == 0)
			{
				isPressed = 1;
				LedControl_SetAllColor(LED_COLOR_BLUE, 100);
				LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_BLUE, 100);
				LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_BLUE, 100);
				BuzzerControl_SendPacketRespond(1);
				BuzzerControl_SetMelody(pbeep);
			}
			else
			{
				isPressed = 0;
				LedControl_SetAllColor(LED_COLOR_BLUE, 0);
				LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_BLUE, 0);
				LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_BLUE, 0);
				BuzzerControl_SendPacketRespond(1);
				BuzzerControl_SetMelody(pbeep);
			}
		}
		break;
		case EVENT_OF_BUTTON_4_PRESS_LOGIC:
		{
			if(isPressed == 0)
			{
				isPressed = 1;
				LedControl_SetAllColor(LED_COLOR_WHITE, 100);
				LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_WHITE, 100);
				LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_WHITE, 100);
				BuzzerControl_SendPacketRespond(1);
				BuzzerControl_SetMelody(pbeep);
			}
			else
			{
				isPressed = 0;
				LedControl_SetAllColor(LED_COLOR_WHITE, 0);
				LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_WHITE, 0);
				LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_WHITE, 0);
				BuzzerControl_SendPacketRespond(1);
				BuzzerControl_SetMelody(pbeep);
			}
		}
		break;
		case EVENT_OF_BUTTON_1_HOLD_1S:
		{

		}
		break;
		case EVENT_OF_BUTTON_1_RELEASED_1S:
		{

		}
		break;
		case EVENT_OF_BUTTON_5_HOLD_1S:
		{

		}
		break;
		case EVENT_OF_BUTTON_5_RELEASED_1S:
		{

		}
		break;
		default:
			break;
	}
}
//Hàm nhận sự kiện bật tắt Led từ phần mềm
void LedCmdSetState(uint8_t led_id, uint8_t led_color, uint8_t led_num_blink, uint8_t led_interval, uint8_t led_last_state)
{
	led_color_t color = led_color;
	//0: Bật led trái màu đỏ
	//4: Tắt led trái
	//1: Bật led trái màu xanh
	//2: Bât led trái màu trắng
	if(led_last_state != 4)
	{
		LedControl_SetColorIndividual(led_id, color, 100);
	}
	else {
		LedControl_SetColorIndividual(led_id, color, 0);
	}
}
//Hàm nhận sự kiện bấm còi từ phần mềm
void BuzzerCmdSetState(uint8_t buzzer_state)
{
	BuzzerControl_SetMelody(pbeep);
}
//Hàm nhận sự kiện viết chuối từ pm lên LCD
void LcdCmdSetState(char* str)
{
	ucg_ClearScreen(&ucg);
	ucg_DrawString(&ucg, 0, 32, 0, str);
}
//Request nhiệt độ độ ẩm ánh sáng và chuyển dữ liệu lên pm
void Task_multiSensorScan(void)
{
		time_current = GetMilSecTick();
		if(time_current >= time_initial)
		{
			time_total += time_current - time_initial;
		}
		else
		{
			time_total += 0xFFFFFFFFU -time_current + time_initial;
		}
		if(time_total >= CYCLE_SEND_DATA)
		{
			time_total = 0;

			ucg_ClearScreen(&ucg);
			ucg_SetFont(&ucg, ucg_font_9x15_tr);

			temperature = (uint8_t)(TemHumSensor_GetTemp()/100);
			humidity = (uint8_t)(TemHumSensor_GetHumi()/100);
			light = LightSensor_MeasureUsePollingMode();


			//Chuyển dữ liệu ánh sáng lên pm
			LightSensor_SendPacketRespond(light);
			//Chuyển dữ liệu độ ẩm lên pm
			HumiSensor_SendPacketRespond(humidity);
			//Chuyển dữ liệu nhiệt độ lên pm
			TempSensor_SendPacketRespond(temperature);

//			memset(scr1, 0, sizeof(src1));
			sprintf(src1, "Temp = %d oC", temperature);
			ucg_DrawString(&ucg, 0, 32, 0, src1);

//			memset(scr2, 0, sizeof(src2));
			sprintf(src2, "Humi = %d", humidity);
			ucg_DrawString(&ucg, 0, 52, 0, src2);
			ucg_DrawString(&ucg, 90, 52, 0, "%");

//			memset(scr2, 0, sizeof(src2));
			sprintf(src3, "Light = %d Lux", light);
			ucg_DrawString(&ucg, 0, 72, 0, src3);
		}
		time_initial = time_current;
}

void delay_ms(uint32_t millisecond)
{
	for(uint32_t volatile i = 0; i < millisecond; i++)
	{
		for(uint32_t volatile j = 0; j < 5000; j++);
	}
}
int main(void)
{
	AppInitCommon();
	SetStateApp(STATE_APP_STARTUP);
	EventSchedulerAdd(EVENT_APP_INIT);
	while(1)
	{
		Task_multiSensorScan();
		processTimerScheduler();
		processEventScheduler();
			();
	}
}
